version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: fc7/jDQz6o7mVl3mNSsxgoun
      POSTGRES_DB: backstage
    ports:
      - "5432:5432"
      
networks:
  mongo-network:
    driver: bridge
